"""GLE file writer for gleplot."""

import numpy as np
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from .config import GLEStyleConfig, GLEGraphConfig, GLEMarkerConfig, GlobalConfig


class GLEWriter:
    """Writer for GLE script files.
    
    Parameters
    ----------
    figsize : tuple, optional
        Figure size (width, height) in inches. Default: (8, 6)
    dpi : int, optional
        Dots per inch for PNG output. Default: 100
    style : GLEStyleConfig, optional
        Style configuration. If None, uses global default.
    graph : GLEGraphConfig, optional
        Graph configuration. If None, uses global default.
    marker : GLEMarkerConfig, optional
        Marker configuration. If None, uses global default.
    """
    
    def __init__(self, figsize: Tuple[float, float] = (8, 6), dpi: int = 100,
                 style: Optional[GLEStyleConfig] = None,
                 graph: Optional[GLEGraphConfig] = None,
                 marker: Optional[GLEMarkerConfig] = None):
        """Initialize GLE writer with optional configuration objects."""
        self.figsize = figsize
        self.dpi = dpi
        # Convert inches to cm (GLE uses cm)
        self.width_cm = figsize[0] * 2.54
        self.height_cm = figsize[1] * 2.54
        
        # Get configuration (fall back to global defaults)
        self.style = style or GlobalConfig.get_style()
        self.graph = graph or GlobalConfig.get_graph()
        self.marker = marker or GlobalConfig.get_marker()
        
        self.lines_gle = []  # GLE script lines
        self.data_files = {}  # {filename: data_content}
        self.dataset_index = 1  # Counter for unique dataset names (d1, d2, d3, ...) - GLE is 1-indexed
    
    def add_preamble(self, include_graph_begin: bool = True):
        """Add GLE preamble.
        
        Includes:
        - Page size setup
        - Font configuration (from style config)
        - Optionally begins the first graph block
        
        Parameters
        ----------
        include_graph_begin : bool
            If True (default), appends 'begin graph' for single-plot
            backward compatibility. Set False for multi-subplot layout.
        """
        self.lines_gle.extend([
            '! GLE graphics file',
            '! Generated by gleplot',
            '',
            f'size {self._format_number(self.width_cm)} {self._format_number(self.height_cm)}',
        ])
        # Only set font if explicitly specified
        if self.style.font:
            self.lines_gle.append(f'set font {self.style.font}')
        self.lines_gle.extend([
            f'set hei {self._format_number(self.style.fontsize / 28.35)}',  # Convert points to cm
            '',
        ])
        if include_graph_begin:
            self.lines_gle.append('begin graph')
    
    def begin_graph(self):
        """Open a new graph block.
        
        Used in multi-subplot layouts. Each graph block must be closed
        with end_graph().
        """
        self.lines_gle.append('begin graph')
    
    def end_graph(self):
        """Close the current graph block."""
        self.lines_gle.append('end graph')
    
    def add_amove(self, x_cm: float, y_cm: float):
        """Add absolute move command to position the next graph.
        
        In GLE, 'amove x y' positions the drawing cursor at absolute
        coordinates (in cm) from the bottom-left of the page.
        
        Parameters
        ----------
        x_cm : float
            X position in cm from the left edge of the page.
        y_cm : float
            Y position in cm from the bottom edge of the page.
        """
        self.lines_gle.append(
            f'amove {self._format_number(x_cm)} {self._format_number(y_cm)}'
        )
    
    def add_graph_size(self, width_cm: Optional[float] = None, height_cm: Optional[float] = None,
                        force_size: bool = False):
        """Set graph dimensions and scaling.
        
        Uses the configured scale_mode (auto, fixed, or fullsize).
        
        Parameters
        ----------
        width_cm : float, optional
            Graph width in cm. Used if scale_mode is 'fixed' or force_size is True.
        height_cm : float, optional
            Graph height in cm. Used if scale_mode is 'fixed' or force_size is True.
        force_size : bool
            If True, always emit the size command regardless of scale_mode.
            Used for subplot layouts where each graph needs an explicit size.
            Subplots use 'scale 1 1' to make plot area fill the entire graph box
            with no padding, so axes from adjacent subplots can touch.
        """
        if force_size and width_cm is not None and height_cm is not None:
            self.lines_gle.append(f'    size {self._format_number(width_cm)} {self._format_number(height_cm)}')
            self.lines_gle.append('    scale 1 1')  # Fill entire graph box for tight subplot layout
        elif self.graph.scale_mode == 'fixed' and width_cm is not None and height_cm is not None:
            self.lines_gle.append(f'    size {self._format_number(width_cm)} {self._format_number(height_cm)}')
            self.lines_gle.append('    scale 1 1')
        elif self.graph.scale_mode == 'fullsize':
            self.lines_gle.append('    fullsize')
        else:  # 'auto' - default
            # Auto-size and center axes within graph box
            self.lines_gle.append('    scale auto')
    
    def add_axes(self, xlabel: Optional[str] = None, ylabel: Optional[str] = None,
                 y2label: Optional[str] = None,
                 title: Optional[str] = None, xlog: bool = False, ylog: bool = False,
                 y2log: bool = False,
                 xmin: Optional[float] = None, xmax: Optional[float] = None,
                 ymin: Optional[float] = None, ymax: Optional[float] = None,
                 y2min: Optional[float] = None, y2max: Optional[float] = None,
                 show_xlabel: bool = True, show_ylabel: bool = True,
                 show_xticks: bool = True, show_yticks: bool = True,
                 remove_last_xtick: bool = False, remove_last_ytick: bool = False,
                 remove_first_xtick: bool = False, remove_first_ytick: bool = False):
        """Add axis configuration.
        
        Parameters
        ----------
        xlabel, ylabel : str, optional
            Axis labels
        y2label : str, optional
            Secondary y-axis (right) label
        title : str, optional
            Plot title
        xlog, ylog : bool
            Whether to use logarithmic scale
        y2log : bool
            Whether to use logarithmic scale for y2axis
        xmin, xmax, ymin, ymax : float, optional
            Axis limits
        y2min, y2max : float, optional
            Secondary y-axis limits
        show_xlabel, show_ylabel : bool
            Whether to display axis TITLES (for shared axes)
        show_xticks, show_yticks : bool
            Whether to display axis tick LABELS/NUMBERS (for shared axes)
        remove_last_xtick, remove_last_ytick : bool
            Whether to remove the last tick label using GLE's nolast command
            (used when subplots touch to avoid overlapping labels)
        remove_first_xtick, remove_first_ytick : bool
            Whether to remove the first tick label using GLE's nofirst command
            (used when subplots touch to avoid overlapping labels)
        """
        if title:
            self.lines_gle.append(f'    title "{title}"')
        
        # Only show axis titles if requested
        # Note: show_xlabel controls the title (e.g. "Time (s)"), not the tick marks
        if xlabel and show_xlabel:
            self.lines_gle.append(f'    xtitle "{xlabel}"')
        
        if ylabel and show_ylabel:
            self.lines_gle.append(f'    ytitle "{ylabel}"')
        
        # Add y2axis title if provided
        if y2label:
            self.lines_gle.append(f'    y2title "{y2label}"')
        
        # Handle axis ranges and tick labels
        # Note: We keep the axis and ticks visible but can hide the tick labels
        x_cmd = '    xaxis'
        if xmin is not None:
            x_cmd += f' min {self._format_number(xmin)}'
        if xmax is not None:
            x_cmd += f' max {self._format_number(xmax)}'
        if xlog:
            x_cmd += ' log'
        if remove_first_xtick:
            x_cmd += ' nofirst'  # Remove first tick label to prevent overlap
        if remove_last_xtick:
            x_cmd += ' nolast'  # Remove last tick label to prevent overlap
        
        # Add xaxis command if it has parameters
        if x_cmd != '    xaxis':
            self.lines_gle.append(x_cmd)
        
        # Hide x-axis tick labels if requested (but keep the ticks themselves)
        if not show_xticks:
            self.lines_gle.append('    xlabels off')
        
        # Same for y-axis
        y_cmd = '    yaxis'
        if ymin is not None:
            y_cmd += f' min {self._format_number(ymin)}'
        if ymax is not None:
            y_cmd += f' max {self._format_number(ymax)}'
        if ylog:
            y_cmd += ' log'
        if remove_first_ytick:
            y_cmd += ' nofirst'  # Remove first tick label to prevent overlap
        if remove_last_ytick:
            y_cmd += ' nolast'  # Remove last tick label to prevent overlap
        
        # Add yaxis command if it has parameters
        if y_cmd != '    yaxis':
            self.lines_gle.append(y_cmd)
        
        # Hide y-axis tick labels if requested (but keep the ticks themselves)
        if not show_yticks:
            self.lines_gle.append('    ylabels off')
        
        # Handle y2axis (secondary y-axis) if limits or log scale specified
        if y2min is not None or y2max is not None or y2log:
            y2_cmd = '    y2axis'
            if y2min is not None:
                y2_cmd += f' min {self._format_number(y2min)}'
            if y2max is not None:
                y2_cmd += f' max {self._format_number(y2max)}'
            if y2log:
                y2_cmd += ' log'
            self.lines_gle.append(y2_cmd)
    
    def add_data_file(self, filename: str, columns: List[np.ndarray],
                      column_names: Optional[List[str]] = None):
        """
        Add external data file.
        
        Parameters
        ----------
        filename : str
            Name of data file (without path)
        columns : list of arrays
            Column data
        column_names : list of str, optional
            Column names/headers
        """
        lines = []
        
        # Write header if provided
        if column_names:
            lines.append(' '.join(column_names))
        
        # Convert columns to 2D array
        data = np.column_stack(columns)
        
        # Write data rows
        for row in data:
            line = ' '.join(self._format_number(val) for val in row)
            lines.append(line)
        
        # Add trailing newline for GLE compatibility
        self.data_files[filename] = '\n'.join(lines) + '\n'
    
    def add_plot_line(self, x: np.ndarray, y: np.ndarray, data_file: str,
                      color: str = 'BLUE', linestyle: str = '-',
                      linewidth: float = 1.0, label: Optional[str] = None,
                      marker: Optional[str] = None, markersize: float = 0.1,
                      yaxis: str = 'y'):
        """
        Add line plot to graph.
        
        Parameters
        ----------
        x, y : arrays
            Data coordinates
        data_file : str
            External data file name
        color : str
            GLE color name
        linestyle : str
            Matplotlib linestyle ('-', '--', ':', '-.')
        linewidth : float
            Line width
        label : str, optional
            Legend label
        marker : str, optional
            GLE marker name
        markersize : float
            Marker size for GLE (msize)
        yaxis : str
            Which y-axis to use: 'y' (left, default) or 'y2' (right)
        """
        # Sort data by x values (required for GLE smooth lines)
        # Reference: GLE manual - smooth requires sorted x values
        x_array = np.asarray(x)
        y_array = np.asarray(y)
        sorted_indices = np.argsort(x_array)
        x_sorted = x_array[sorted_indices]
        y_sorted = y_array[sorted_indices]
        
        # Add data file with sorted data
        self.add_data_file(data_file, [x_sorted, y_sorted])
        
        # Generate plot command with unique dataset name
        d_name = f'd{self.dataset_index}'
        self.dataset_index += 1
        
        cmd = f'    data {data_file} {d_name}=c1,c2'
        self.lines_gle.append(cmd)
        
        # Generate line command
        line_cmd = f'    {d_name}'
        
        # Convert matplotlib linewidth (points) to GLE lwidth (cm)
        # If linewidth is 0 or 1, use default from style config
        if linewidth == 0 or linewidth == 1:
            gle_lwidth = self.style.default_linewidth * 0.03528  # pt to cm
        else:
            gle_lwidth = linewidth * 0.03528  # 1 point = 1/72 inch = 0.03528 cm
        
        if marker:
            # Scatter plot (no line)
            line_cmd += f' marker {marker} msize {self._format_number(markersize)} color {color}'
        else:
            # Line plot with optional smooth curves (configured via graph.smooth_curves)
            if self.graph.smooth_curves:
                line_cmd += ' line smooth'
            else:
                line_cmd += ' line'
            line_cmd += f' color {color} lwidth {self._format_number(gle_lwidth)}'
            
            # Use configured line styles from style config
            if linestyle == '--':
                line_cmd += f' lstyle {self.style.line_style_dashed}'
            elif linestyle == ':':
                line_cmd += f' lstyle {self.style.line_style_dotted}'
            elif linestyle == '-.':
                line_cmd += f' lstyle {self.style.line_style_dashdot}'
                line_cmd += ' lstyle 4'
        
        # Add y2axis directive if using secondary y-axis
        if yaxis == 'y2':
            line_cmd += ' y2axis'
        
        if label:
            line_cmd += f' key "{label}"'
        
        self.lines_gle.append(line_cmd)
    
    def add_bar_chart(self, x: np.ndarray, heights: np.ndarray, data_file: str,
                      colors: Optional[List[str]] = None, label: Optional[str] = None):
        """
        Add bar chart to graph.
        
        GLE bar chart implementation uses a single dataset with multiple rows.
        All bars use the same color due to GLE limitations.
        
        Parameters
        ----------
        x : array
            Bar positions (categories)
        heights : array
            Bar heights
        data_file : str
            Data file name
        colors : list of str, optional
            GLE color names. Only the first color is used; all bars will
            have the same color due to GLE limitations.
        label : str, optional
            Legend label (not currently supported by GLE for bar charts)
        """
        x = np.asarray(x, dtype=float)
        heights = np.asarray(heights, dtype=float)
        
        # Default to RED if no colors provided
        if colors is None:
            bar_color = 'RED'
        else:
            # Use first color only - GLE doesn't support per-bar coloring in single dataset
            bar_color = colors[0]
        
        # Create single data file with all bars (multiple rows)
        self.add_data_file(data_file, [x, heights])
        
        # Add data command
        d_name = f'd{self.dataset_index}'
        self.dataset_index += 1
        
        cmd = f'    data {data_file} {d_name}=c1,c2'
        self.lines_gle.append(cmd)
        
        # GLE bar syntax for single dataset: bar d1 fill color
        bar_cmd = f'    bar {d_name} fill {bar_color}'
        
        # Note: GLE does not support 'key' parameter on bar commands
        # Legend entries for bar charts need alternative implementation
        
        self.lines_gle.append(bar_cmd)
    
    def add_errorbar(self, x: np.ndarray, y: np.ndarray, data_file: str,
                     color: str = 'BLUE', linestyle: str = '-',
                     linewidth: float = 1.0, label: Optional[str] = None,
                     marker: Optional[str] = None, markersize: float = 0.1,
                     yerr_up: Optional[np.ndarray] = None,
                     yerr_down: Optional[np.ndarray] = None,
                     xerr_left: Optional[np.ndarray] = None,
                     xerr_right: Optional[np.ndarray] = None,
                     capsize: Optional[float] = None,
                     yaxis: str = 'y'):
        """
        Add plot with error bars to graph.
        
        Generates GLE error bar syntax using datasets for error values.
        
        GLE error bar syntax reference (from GLE manual):
        - ``dn err <value|percent|dataset>`` — symmetric vertical errors
        - ``dn errup <value|percent|dataset>`` — upper vertical error
        - ``dn errdown <value|percent|dataset>`` — lower vertical error
        - ``dn errwidth <width>`` — vertical error bar cap width
        - ``dn herr <value|percent|dataset>`` — symmetric horizontal errors
        - ``dn herrleft <value|percent|dataset>`` — left horizontal error
        - ``dn herrright <value|percent|dataset>`` — right horizontal error
        - ``dn herrwidth <width>`` — horizontal error bar cap width
        
        Parameters
        ----------
        x, y : arrays
            Data coordinates
        data_file : str
            External data file name
        color : str
            GLE color name
        linestyle : str
            Matplotlib linestyle ('-', '--', ':', '-.')
        linewidth : float
            Line width
        label : str, optional
            Legend label
        marker : str, optional
            GLE marker name
        markersize : float
            Marker size for GLE (msize)
        yerr_up : array, optional
            Upward vertical error bar magnitudes
        yerr_down : array, optional
            Downward vertical error bar magnitudes
        xerr_left : array, optional
            Leftward horizontal error bar magnitudes
        xerr_right : array, optional
            Rightward horizontal error bar magnitudes
        capsize : float, optional
            Width of error bar caps in cm
        yaxis : str
            Which y-axis to use: 'y' (left, default) or 'y2' (right)
        """
        # Sort data by x values
        x_array = np.asarray(x)
        y_array = np.asarray(y)
        sorted_indices = np.argsort(x_array)
        x_sorted = x_array[sorted_indices]
        y_sorted = y_array[sorted_indices]
        
        # Build columns list: x, y, then error columns
        columns = [x_sorted, y_sorted]
        col_idx = 3  # Next column index (c1=x, c2=y, c3=...)
        
        # Track which columns hold error data
        yerr_up_col = None
        yerr_down_col = None
        xerr_left_col = None
        xerr_right_col = None
        
        has_yerr = yerr_up is not None or yerr_down is not None
        has_xerr = xerr_left is not None or xerr_right is not None
        
        # Check if vertical errors are symmetric (same arrays)
        yerr_symmetric = (has_yerr and yerr_up is not None and yerr_down is not None
                         and np.array_equal(yerr_up, yerr_down))
        # Check if horizontal errors are symmetric
        xerr_symmetric = (has_xerr and xerr_left is not None and xerr_right is not None
                         and np.array_equal(xerr_left, xerr_right))
        
        if has_yerr:
            if yerr_symmetric:
                # Single column for symmetric error
                columns.append(np.asarray(yerr_up)[sorted_indices])
                yerr_up_col = col_idx
                yerr_down_col = col_idx  # Same column
                col_idx += 1
            else:
                if yerr_up is not None:
                    columns.append(np.asarray(yerr_up)[sorted_indices])
                    yerr_up_col = col_idx
                    col_idx += 1
                if yerr_down is not None:
                    columns.append(np.asarray(yerr_down)[sorted_indices])
                    yerr_down_col = col_idx
                    col_idx += 1
        
        if has_xerr:
            if xerr_symmetric:
                columns.append(np.asarray(xerr_left)[sorted_indices])
                xerr_left_col = col_idx
                xerr_right_col = col_idx
                col_idx += 1
            else:
                if xerr_left is not None:
                    columns.append(np.asarray(xerr_left)[sorted_indices])
                    xerr_left_col = col_idx
                    col_idx += 1
                if xerr_right is not None:
                    columns.append(np.asarray(xerr_right)[sorted_indices])
                    xerr_right_col = col_idx
                    col_idx += 1
        
        # Write data file with all columns
        self.add_data_file(data_file, columns)
        
        # Generate dataset name for main data
        d_main = f'd{self.dataset_index}'
        self.dataset_index += 1
        
        # Build data command with all dataset references
        data_cmd = f'    data {data_file} {d_main}=c1,c2'
        
        # Create error datasets referencing the same file columns
        err_datasets = {}
        
        if has_yerr:
            if yerr_symmetric:
                d_yerr = f'd{self.dataset_index}'
                self.dataset_index += 1
                data_cmd += f' {d_yerr}=c1,c{yerr_up_col}'
                err_datasets['yerr'] = d_yerr
            else:
                if yerr_up_col is not None:
                    d_yerr_up = f'd{self.dataset_index}'
                    self.dataset_index += 1
                    data_cmd += f' {d_yerr_up}=c1,c{yerr_up_col}'
                    err_datasets['yerr_up'] = d_yerr_up
                if yerr_down_col is not None:
                    d_yerr_down = f'd{self.dataset_index}'
                    self.dataset_index += 1
                    data_cmd += f' {d_yerr_down}=c1,c{yerr_down_col}'
                    err_datasets['yerr_down'] = d_yerr_down
        
        if has_xerr:
            if xerr_symmetric:
                d_xerr = f'd{self.dataset_index}'
                self.dataset_index += 1
                data_cmd += f' {d_xerr}=c1,c{xerr_left_col}'
                err_datasets['xerr'] = d_xerr
            else:
                if xerr_left_col is not None:
                    d_xerr_left = f'd{self.dataset_index}'
                    self.dataset_index += 1
                    data_cmd += f' {d_xerr_left}=c1,c{xerr_left_col}'
                    err_datasets['xerr_left'] = d_xerr_left
                if xerr_right_col is not None:
                    d_xerr_right = f'd{self.dataset_index}'
                    self.dataset_index += 1
                    data_cmd += f' {d_xerr_right}=c1,c{xerr_right_col}'
                    err_datasets['xerr_right'] = d_xerr_right
        
        self.lines_gle.append(data_cmd)
        
        # Build the main dataset display command
        line_cmd = f'    {d_main}'
        
        # Convert linewidth
        if linewidth == 0 or linewidth == 1:
            gle_lwidth = self.style.default_linewidth * 0.03528
        else:
            gle_lwidth = linewidth * 0.03528
        
        # Add line/marker styling
        if marker:
            line_cmd += f' marker {marker} msize {self._format_number(markersize)} color {color}'
            # Also add line if linestyle is not 'none'
            if linestyle not in ('', 'none', ' ', 'None'):
                line_cmd += f' line lwidth {self._format_number(gle_lwidth)}'
                if linestyle == '--':
                    line_cmd += f' lstyle {self.style.line_style_dashed}'
                elif linestyle == ':':
                    line_cmd += f' lstyle {self.style.line_style_dotted}'
                elif linestyle == '-.':
                    line_cmd += f' lstyle {self.style.line_style_dashdot}'
        else:
            if linestyle not in ('', 'none', ' ', 'None'):
                if self.graph.smooth_curves:
                    line_cmd += ' line smooth'
                else:
                    line_cmd += ' line'
                line_cmd += f' color {color} lwidth {self._format_number(gle_lwidth)}'
                if linestyle == '--':
                    line_cmd += f' lstyle {self.style.line_style_dashed}'
                elif linestyle == ':':
                    line_cmd += f' lstyle {self.style.line_style_dotted}'
                elif linestyle == '-.':
                    line_cmd += f' lstyle {self.style.line_style_dashdot}'
        
        # Add vertical error bar commands
        if 'yerr' in err_datasets:
            line_cmd += f' err {err_datasets["yerr"]}'
        else:
            if 'yerr_up' in err_datasets:
                line_cmd += f' errup {err_datasets["yerr_up"]}'
            if 'yerr_down' in err_datasets:
                line_cmd += f' errdown {err_datasets["yerr_down"]}'
        
        if capsize is not None and has_yerr:
            line_cmd += f' errwidth {self._format_number(capsize)}'
        
        # Add horizontal error bar commands
        if 'xerr' in err_datasets:
            line_cmd += f' herr {err_datasets["xerr"]}'
        else:
            if 'xerr_left' in err_datasets:
                line_cmd += f' herrleft {err_datasets["xerr_left"]}'
            if 'xerr_right' in err_datasets:
                line_cmd += f' herrright {err_datasets["xerr_right"]}'
        
        if capsize is not None and has_xerr:
            line_cmd += f' herrwidth {self._format_number(capsize)}'
        
        # Add y2axis directive if using secondary y-axis
        if yaxis == 'y2':
            line_cmd += ' y2axis'
        
        if label:
            line_cmd += f' key "{label}"'
        
        self.lines_gle.append(line_cmd)

    def add_errorbar_from_file(
        self,
        data_file: str,
        x_col: int,
        y_col: int,
        yerr_col: Optional[int] = None,
        color: str = 'BLUE',
        marker: Optional[str] = None,
        markersize: float = 0.1,
        label: Optional[str] = None,
        capsize: Optional[float] = None,
        yaxis: str = 'y',
    ):
        """Add a marker/errorbar series that references columns in an external data file."""
        d_main = f'd{self.dataset_index}'
        self.dataset_index += 1

        data_cmd = f'    data {data_file} {d_main}=c{x_col},c{y_col}'
        d_yerr = None
        if yerr_col is not None:
            d_yerr = f'd{self.dataset_index}'
            self.dataset_index += 1
            data_cmd += f' {d_yerr}=c{x_col},c{yerr_col}'
        self.lines_gle.append(data_cmd)

        line_cmd = f'    {d_main}'
        if marker:
            line_cmd += f' marker {marker} msize {self._format_number(markersize)} color {color}'
        else:
            line_cmd += f' color {color}'

        if d_yerr is not None:
            line_cmd += f' err {d_yerr}'
            if capsize is not None:
                line_cmd += f' errwidth {self._format_number(capsize)}'

        if yaxis == 'y2':
            line_cmd += ' y2axis'

        if label:
            line_cmd += f' key "{label}"'

        self.lines_gle.append(line_cmd)
    
    def add_fill_between(self, x: np.ndarray, y1: np.ndarray, y2: np.ndarray,
                         data_file: str, color: str = 'LIGHTBLUE', alpha: float = 1.0):
        """
        Add fill between two curves.
        
        Parameters
        ----------
        x, y1, y2 : arrays
            x coordinates and two y series
        data_file : str
            External data file name
        color : str
            GLE fill color
        alpha : float
            Transparency (not directly supported in GLE, but stored)
        """
        self.add_data_file(data_file, [x, y1, y2])
        
        # Create two unique dataset names for the fill between operation
        d1_name = f'd{self.dataset_index}'
        d2_name = f'd{self.dataset_index + 1}'
        self.dataset_index += 2
        
        cmd = f'    data {data_file} {d1_name}=c1,c2 {d2_name}=c1,c3'
        self.lines_gle.append(cmd)
        
        # GLE fill between two datasets: fill d1,d2 color X
        self.lines_gle.append(f'    fill {d1_name},{d2_name} color {color}')
    
    def add_legend(self, position: Optional[str] = None):
        """Add legend configuration.
        
        Parameters
        ----------
        position : str, optional
            Legend position. If None, uses configured default.
            Options: 'tl', 'tr', 'bl', 'br', 'tc', 'bc', 'lc', 'rc', 'cc'
            or long form: 'top right', 'top left', 'bottom right', 'bottom left', 'center'
        """
        # Use provided position or fall back to configured default
        pos = position if position is not None else self.graph.legend_position
        
        pos_map = {
            'top right': 'tr',
            'top left': 'tl',
            'bottom right': 'br',
            'bottom left': 'bl',
            'center': 'cc',
        }
        gle_pos = pos_map.get(pos, pos)  # Try long form, else use as-is (short form)
        self.lines_gle.append(f'    key pos {gle_pos}')
    
    def finalize(self, include_graph_end: bool = True):
        """Add closing statements.
        
        Parameters
        ----------
        include_graph_end : bool
            If True (default), appends 'end graph' for single-plot
            backward compatibility. Set False for multi-subplot layout.
        """
        if include_graph_end:
            self.lines_gle.extend([
                'end graph',
            ])
    
    def get_gle_content(self) -> str:
        """Get complete GLE script content."""
        return '\n'.join(self.lines_gle)
    
    def write_files(self, output_dir: str, base_filename: str = 'plot'):
        """
        Write GLE script and data files.
        
        Parameters
        ----------
        output_dir : str
            Directory for output files
        base_filename : str
            Base name for files (without extension)
            
        Returns
        -------
        dict
            Mapping of filename to full path
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        files = {}
        
        # Write GLE script
        gle_file = output_dir / f'{base_filename}.gle'
        gle_file.write_text(self.get_gle_content())
        files['script'] = gle_file
        
        # Write data files
        for data_file, content in self.data_files.items():
            data_path = output_dir / data_file
            data_path.write_text(content)
            files[data_file] = data_path
        
        return files
    
    @staticmethod
    def _format_number(val: float, precision: int = 6) -> str:
        """Format number for GLE output."""
        if isinstance(val, (int, float)):
            if abs(val) < 1e-10:
                return '0'
            if abs(val) > 1e10:
                return f'{val:.3e}'
            # Use general format with reasonable precision
            formatted = f'{val:.{precision}g}'
            return formatted
        return str(val)
