"""GLE file writer for gleplot."""

import numpy as np
from pathlib import Path
from typing import List, Dict, Optional, Tuple


class GLEWriter:
    """Writer for GLE script files."""
    
    def __init__(self, figsize: Tuple[float, float] = (8, 6), dpi: int = 100):
        """
        Initialize GLE writer.
        
        Parameters
        ----------
        figsize : tuple
            Figure size (width, height) in inches
        dpi : int
            Dots per inch for GLE sizing
        """
        self.figsize = figsize
        self.dpi = dpi
        # Convert inches to cm (GLE uses cm)
        self.width_cm = figsize[0] * 2.54
        self.height_cm = figsize[1] * 2.54
        
        self.lines_gle = []  # GLE script lines
        self.data_files = {}  # {filename: data_content}
    
    def add_preamble(self):
        """Add GLE preamble."""
        self.lines_gle.extend([
            '! GLE graphics file',
            '! Generated by gleplot',
            '',
            f'size {self.width_cm} {self.height_cm}',
            'set font texcmr',
            'amove 1 1',
            'begin graph',
        ])
    
    def add_graph_size(self, width_cm: float = 15, height_cm: float = 10):
        """Set graph dimensions."""
        self.lines_gle.append(f'    size {width_cm} {height_cm}')
    
    def add_axes(self, xlabel: Optional[str] = None, ylabel: Optional[str] = None,
                 title: Optional[str] = None, xlog: bool = False, ylog: bool = False,
                 xmin: Optional[float] = None, xmax: Optional[float] = None,
                 ymin: Optional[float] = None, ymax: Optional[float] = None):
        """Add axis configuration."""
        if title:
            self.lines_gle.append(f'    title "{title}"')
        
        if xlabel:
            self.lines_gle.append(f'    xtitle "{xlabel}"')
        
        if ylabel:
            self.lines_gle.append(f'    ytitle "{ylabel}"')
        
        # Handle axis ranges
        x_cmd = '    xaxis'
        if xmin is not None:
            x_cmd += f' min {self._format_number(xmin)}'
        if xmax is not None:
            x_cmd += f' max {self._format_number(xmax)}'
        if xlog:
            x_cmd += ' log on'
        if 'min' in x_cmd or 'max' in x_cmd or 'log' in x_cmd:
            self.lines_gle.append(x_cmd)
        
        y_cmd = '    yaxis'
        if ymin is not None:
            y_cmd += f' min {self._format_number(ymin)}'
        if ymax is not None:
            y_cmd += f' max {self._format_number(ymax)}'
        if ylog:
            y_cmd += ' log on'
        if 'min' in y_cmd or 'max' in y_cmd or 'log' in y_cmd:
            self.lines_gle.append(y_cmd)
    
    def add_data_file(self, filename: str, columns: List[np.ndarray],
                      column_names: Optional[List[str]] = None):
        """
        Add external data file.
        
        Parameters
        ----------
        filename : str
            Name of data file (without path)
        columns : list of arrays
            Column data
        column_names : list of str, optional
            Column names/headers
        """
        lines = []
        
        # Write header if provided
        if column_names:
            lines.append(' '.join(column_names))
        
        # Convert columns to 2D array
        data = np.column_stack(columns)
        
        # Write data rows
        for row in data:
            line = ' '.join(self._format_number(val) for val in row)
            lines.append(line)
        
        self.data_files[filename] = '\n'.join(lines)
    
    def add_plot_line(self, x: np.ndarray, y: np.ndarray, data_file: str,
                      color: str = 'BLUE', linestyle: str = '-',
                      linewidth: float = 1.0, label: Optional[str] = None,
                      marker: Optional[str] = None, markersize: float = 0.1):
        """
        Add line plot to graph.
        
        Parameters
        ----------
        x, y : arrays
            Data coordinates
        data_file : str
            External data file name
        color : str
            GLE color name
        linestyle : str
            Matplotlib linestyle ('-', '--', ':', '-.')
        linewidth : float
            Line width
        label : str, optional
            Legend label
        marker : str, optional
            GLE marker name
        markersize : float
            Marker size for GLE (msize)
        """
        # Add data file
        self.add_data_file(data_file, [x, y])
        
        # Generate plot command
        d_index = len(self.data_files) - 1
        cmd = f'    data {data_file} d{d_index}=c1,c2'
        self.lines_gle.append(cmd)
        
        # Generate line command
        line_cmd = f'    d{d_index}'
        
        if marker:
            # Scatter plot (no line)
            line_cmd += f' marker {marker} msize {markersize} color {color}'
        else:
            # Line plot
            line_cmd += f' line color {color} lwidth {linewidth}'
            
            if linestyle == '--':
                line_cmd += ' lstyle 2'
            elif linestyle == ':':
                line_cmd += ' lstyle 3'
            elif linestyle == '-.':
                line_cmd += ' lstyle 4'
        
        if label:
            line_cmd += f' key "{label}"'
        
        self.lines_gle.append(line_cmd)
    
    def add_bar_chart(self, x: np.ndarray, heights: np.ndarray, data_file: str,
                      colors: Optional[List[str]] = None, label: Optional[str] = None):
        """
        Add bar chart to graph.
        
        Parameters
        ----------
        x : array
            Bar positions (categories)
        heights : array
            Bar heights
        data_file : str
            External data file name
        colors : list of str, optional
            GLE color names for each bar
        label : str, optional
            Legend label
        """
        self.add_data_file(data_file, [x, heights])
        
        d_index = len(self.data_files) - 1
        cmd = f'    data {data_file} d{d_index}=c1,c2'
        self.lines_gle.append(cmd)
        
        bar_cmd = f'    bar d{d_index}'
        if colors:
            color_str = ','.join(colors)
            bar_cmd += f' color {color_str}'
        else:
            bar_cmd += ' color RED'
        
        bar_cmd += ' fill SHADE2 dist 1 width 0.8'
        
        if label:
            bar_cmd += f' key "{label}"'
        
        self.lines_gle.append(bar_cmd)
    
    def add_fill_between(self, x: np.ndarray, y1: np.ndarray, y2: np.ndarray,
                         data_file: str, color: str = 'LIGHTBLUE', alpha: float = 1.0):
        """
        Add fill between two curves.
        
        Parameters
        ----------
        x, y1, y2 : arrays
            x coordinates and two y series
        data_file : str
            External data file name
        color : str
            GLE fill color
        alpha : float
            Transparency (not directly supported in GLE, but stored)
        """
        self.add_data_file(data_file, [x, y1, y2])
        
        d1_index = len(self.data_files) - 1
        cmd = f'    data {data_file} d{d1_index}=c1,c2 d{d1_index+1}=c1,c3'
        self.lines_gle.append(cmd)
        
        fill_cmd = f'    fill d{d1_index},d{d1_index+1} color {color}'
        self.lines_gle.append(fill_cmd)
    
    def add_legend(self, position: str = 'tr'):
        """Add legend configuration."""
        pos_map = {
            'top right': 'tr',
            'top left': 'tl',
            'bottom right': 'br',
            'bottom left': 'bl',
            'center': 'c',
        }
        gle_pos = pos_map.get(position, 'tr')
        self.lines_gle.append(f'    key pos {gle_pos}')
    
    def finalize(self):
        """Add closing statements."""
        self.lines_gle.extend([
            'end graph',
        ])
    
    def get_gle_content(self) -> str:
        """Get complete GLE script content."""
        return '\n'.join(self.lines_gle)
    
    def write_files(self, output_dir: str, base_filename: str = 'plot'):
        """
        Write GLE script and data files.
        
        Parameters
        ----------
        output_dir : str
            Directory for output files
        base_filename : str
            Base name for files (without extension)
            
        Returns
        -------
        dict
            Mapping of filename to full path
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        files = {}
        
        # Write GLE script
        gle_file = output_dir / f'{base_filename}.gle'
        gle_file.write_text(self.get_gle_content())
        files['script'] = gle_file
        
        # Write data files
        for data_file, content in self.data_files.items():
            data_path = output_dir / data_file
            data_path.write_text(content)
            files[data_file] = data_path
        
        return files
    
    @staticmethod
    def _format_number(val: float, precision: int = 6) -> str:
        """Format number for GLE output."""
        if isinstance(val, (int, float)):
            if abs(val) < 1e-10:
                return '0'
            if abs(val) > 1e10:
                return f'{val:.3e}'
            # Use general format with reasonable precision
            formatted = f'{val:.{precision}g}'
            return formatted
        return str(val)
