"""GLE file writer for gleplot."""

import numpy as np
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from .config import GLEStyleConfig, GLEGraphConfig, GLEMarkerConfig, GlobalConfig


class GLEWriter:
    """Writer for GLE script files.
    
    Parameters
    ----------
    figsize : tuple, optional
        Figure size (width, height) in inches. Default: (8, 6)
    dpi : int, optional
        Dots per inch for PNG output. Default: 100
    style : GLEStyleConfig, optional
        Style configuration. If None, uses global default.
    graph : GLEGraphConfig, optional
        Graph configuration. If None, uses global default.
    marker : GLEMarkerConfig, optional
        Marker configuration. If None, uses global default.
    """
    
    def __init__(self, figsize: Tuple[float, float] = (8, 6), dpi: int = 100,
                 style: Optional[GLEStyleConfig] = None,
                 graph: Optional[GLEGraphConfig] = None,
                 marker: Optional[GLEMarkerConfig] = None):
        """Initialize GLE writer with optional configuration objects."""
        self.figsize = figsize
        self.dpi = dpi
        # Convert inches to cm (GLE uses cm)
        self.width_cm = figsize[0] * 2.54
        self.height_cm = figsize[1] * 2.54
        
        # Get configuration (fall back to global defaults)
        self.style = style or GlobalConfig.get_style()
        self.graph = graph or GlobalConfig.get_graph()
        self.marker = marker or GlobalConfig.get_marker()
        
        self.lines_gle = []  # GLE script lines
        self.data_files = {}  # {filename: data_content}
        self.dataset_index = 1  # Counter for unique dataset names (d1, d2, d3, ...) - GLE is 1-indexed
    
    def add_preamble(self):
        """Add GLE preamble.
        
        Includes:
        - Page size setup
        - Font configuration (from style config)
        - Graph block initialization
        """
        self.lines_gle.extend([
            '! GLE graphics file',
            '! Generated by gleplot',
            '',
            f'size {self._format_number(self.width_cm)} {self._format_number(self.height_cm)}',
            f'set font {self.style.font}',
            f'set hei {self._format_number(self.style.fontsize / 28.35)}',  # Convert points to cm
            '',
            'begin graph',
        ])
    
    def add_graph_size(self, width_cm: Optional[float] = None, height_cm: Optional[float] = None):
        """Set graph dimensions and scaling.
        
        Uses the configured scale_mode (auto, fixed, or fullsize).
        
        Parameters
        ----------
        width_cm : float, optional
            Graph width in cm. Only used if scale_mode is 'fixed'.
        height_cm : float, optional
            Graph height in cm. Only used if scale_mode is 'fixed'.
        """
        if self.graph.scale_mode == 'fixed' and width_cm is not None and height_cm is not None:
            self.lines_gle.append(f'    size {self._format_number(width_cm)} {self._format_number(height_cm)}')
            self.lines_gle.append('    scale 1 1')
        elif self.graph.scale_mode == 'fullsize':
            self.lines_gle.append('    fullsize')
        else:  # 'auto' - default
            # Auto-size and center axes within graph box
            self.lines_gle.append('    scale auto')
    
    def add_axes(self, xlabel: Optional[str] = None, ylabel: Optional[str] = None,
                 title: Optional[str] = None, xlog: bool = False, ylog: bool = False,
                 xmin: Optional[float] = None, xmax: Optional[float] = None,
                 ymin: Optional[float] = None, ymax: Optional[float] = None):
        """Add axis configuration."""
        if title:
            self.lines_gle.append(f'    title "{title}"')
        
        if xlabel:
            self.lines_gle.append(f'    xtitle "{xlabel}"')
        
        if ylabel:
            self.lines_gle.append(f'    ytitle "{ylabel}"')
        
        # Handle axis ranges
        x_cmd = '    xaxis'
        if xmin is not None:
            x_cmd += f' min {self._format_number(xmin)}'
        if xmax is not None:
            x_cmd += f' max {self._format_number(xmax)}'
        if xlog:
            x_cmd += ' log'
        if x_cmd != '    xaxis':
            self.lines_gle.append(x_cmd)
        
        y_cmd = '    yaxis'
        if ymin is not None:
            y_cmd += f' min {self._format_number(ymin)}'
        if ymax is not None:
            y_cmd += f' max {self._format_number(ymax)}'
        if ylog:
            y_cmd += ' log'
        if y_cmd != '    yaxis':
            self.lines_gle.append(y_cmd)
    
    def add_data_file(self, filename: str, columns: List[np.ndarray],
                      column_names: Optional[List[str]] = None):
        """
        Add external data file.
        
        Parameters
        ----------
        filename : str
            Name of data file (without path)
        columns : list of arrays
            Column data
        column_names : list of str, optional
            Column names/headers
        """
        lines = []
        
        # Write header if provided
        if column_names:
            lines.append(' '.join(column_names))
        
        # Convert columns to 2D array
        data = np.column_stack(columns)
        
        # Write data rows
        for row in data:
            line = ' '.join(self._format_number(val) for val in row)
            lines.append(line)
        
        self.data_files[filename] = '\n'.join(lines)
    
    def add_plot_line(self, x: np.ndarray, y: np.ndarray, data_file: str,
                      color: str = 'BLUE', linestyle: str = '-',
                      linewidth: float = 1.0, label: Optional[str] = None,
                      marker: Optional[str] = None, markersize: float = 0.1):
        """
        Add line plot to graph.
        
        Parameters
        ----------
        x, y : arrays
            Data coordinates
        data_file : str
            External data file name
        color : str
            GLE color name
        linestyle : str
            Matplotlib linestyle ('-', '--', ':', '-.')
        linewidth : float
            Line width
        label : str, optional
            Legend label
        marker : str, optional
            GLE marker name
        markersize : float
            Marker size for GLE (msize)
        """
        # Sort data by x values (required for GLE smooth lines)
        # Reference: GLE manual - smooth requires sorted x values
        x_array = np.asarray(x)
        y_array = np.asarray(y)
        sorted_indices = np.argsort(x_array)
        x_sorted = x_array[sorted_indices]
        y_sorted = y_array[sorted_indices]
        
        # Add data file with sorted data
        self.add_data_file(data_file, [x_sorted, y_sorted])
        
        # Generate plot command with unique dataset name
        d_name = f'd{self.dataset_index}'
        self.dataset_index += 1
        
        cmd = f'    data {data_file} {d_name}=c1,c2'
        self.lines_gle.append(cmd)
        
        # Generate line command
        line_cmd = f'    {d_name}'
        
        # Convert matplotlib linewidth (points) to GLE lwidth (cm)
        # If linewidth is 0 or 1, use default from style config
        if linewidth == 0 or linewidth == 1:
            gle_lwidth = self.style.default_linewidth * 0.03528  # pt to cm
        else:
            gle_lwidth = linewidth * 0.03528  # 1 point = 1/72 inch = 0.03528 cm
        
        if marker:
            # Scatter plot (no line)
            line_cmd += f' marker {marker} msize {self._format_number(markersize)} color {color}'
        else:
            # Line plot with optional smooth curves (configured via graph.smooth_curves)
            if self.graph.smooth_curves:
                line_cmd += ' line smooth'
            else:
                line_cmd += ' line'
            line_cmd += f' color {color} lwidth {self._format_number(gle_lwidth)}'
            
            # Use configured line styles from style config
            if linestyle == '--':
                line_cmd += f' lstyle {self.style.line_style_dashed}'
            elif linestyle == ':':
                line_cmd += f' lstyle {self.style.line_style_dotted}'
            elif linestyle == '-.':
                line_cmd += f' lstyle {self.style.line_style_dashdot}'
                line_cmd += ' lstyle 4'
        
        if label:
            line_cmd += f' key "{label}"'
        
        self.lines_gle.append(line_cmd)
    
    def add_bar_chart(self, x: np.ndarray, heights: np.ndarray, data_file: str,
                      colors: Optional[List[str]] = None, label: Optional[str] = None):
        """
        Add bar chart to graph.
        
        Parameters
        ----------
        x : array
            Bar positions (categories)
        heights : array
            Bar heights
        data_file : str
            External data file name
        colors : list of str, optional
            GLE color names for each bar
        label : str, optional
            Legend label
        """
        self.add_data_file(data_file, [x, heights])
        
        d_name = f'd{self.dataset_index}'
        self.dataset_index += 1
        
        cmd = f'    data {data_file} {d_name}=c1,c2'
        self.lines_gle.append(cmd)
        
        # GLE bar syntax: bar d1 fill color [width w]
        # Note: 'fill' sets the fill color, 'color' sets the outline
        fill_color = colors[0] if colors else 'RED'
        bar_cmd = f'    bar {d_name} fill {fill_color}'
        
        self.lines_gle.append(bar_cmd)
    
    def add_fill_between(self, x: np.ndarray, y1: np.ndarray, y2: np.ndarray,
                         data_file: str, color: str = 'LIGHTBLUE', alpha: float = 1.0):
        """
        Add fill between two curves.
        
        Parameters
        ----------
        x, y1, y2 : arrays
            x coordinates and two y series
        data_file : str
            External data file name
        color : str
            GLE fill color
        alpha : float
            Transparency (not directly supported in GLE, but stored)
        """
        self.add_data_file(data_file, [x, y1, y2])
        
        # Create two unique dataset names for the fill between operation
        d1_name = f'd{self.dataset_index}'
        d2_name = f'd{self.dataset_index + 1}'
        self.dataset_index += 2
        
        cmd = f'    data {data_file} {d1_name}=c1,c2 {d2_name}=c1,c3'
        self.lines_gle.append(cmd)
        
        # GLE fill between two datasets: fill d1,d2 color X
        self.lines_gle.append(f'    fill {d1_name},{d2_name} color {color}')
    
    def add_legend(self, position: Optional[str] = None):
        """Add legend configuration.
        
        Parameters
        ----------
        position : str, optional
            Legend position. If None, uses configured default.
            Options: 'tl', 'tr', 'bl', 'br', 'tc', 'bc', 'lc', 'rc', 'cc'
            or long form: 'top right', 'top left', 'bottom right', 'bottom left', 'center'
        """
        # Use provided position or fall back to configured default
        pos = position if position is not None else self.graph.legend_position
        
        pos_map = {
            'top right': 'tr',
            'top left': 'tl',
            'bottom right': 'br',
            'bottom left': 'bl',
            'center': 'cc',
        }
        gle_pos = pos_map.get(pos, pos)  # Try long form, else use as-is (short form)
        self.lines_gle.append(f'    key pos {gle_pos}')
    
    def finalize(self):
        """Add closing statements."""
        self.lines_gle.extend([
            'end graph',
        ])
    
    def get_gle_content(self) -> str:
        """Get complete GLE script content."""
        return '\n'.join(self.lines_gle)
    
    def write_files(self, output_dir: str, base_filename: str = 'plot'):
        """
        Write GLE script and data files.
        
        Parameters
        ----------
        output_dir : str
            Directory for output files
        base_filename : str
            Base name for files (without extension)
            
        Returns
        -------
        dict
            Mapping of filename to full path
        """
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        files = {}
        
        # Write GLE script
        gle_file = output_dir / f'{base_filename}.gle'
        gle_file.write_text(self.get_gle_content())
        files['script'] = gle_file
        
        # Write data files
        for data_file, content in self.data_files.items():
            data_path = output_dir / data_file
            data_path.write_text(content)
            files[data_file] = data_path
        
        return files
    
    @staticmethod
    def _format_number(val: float, precision: int = 6) -> str:
        """Format number for GLE output."""
        if isinstance(val, (int, float)):
            if abs(val) < 1e-10:
                return '0'
            if abs(val) > 1e10:
                return f'{val:.3e}'
            # Use general format with reasonable precision
            formatted = f'{val:.{precision}g}'
            return formatted
        return str(val)
